# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

class RobotType(object):
    PAINT_TOWER = 0
    MONEY_TOWER = 1
    DEFENSE_TOWER = 2
    SOLDIER = 3
    SPLASHER = 4
    MOPPER = 5
