# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

class WinType(object):
    RESIGNATION = 0
    AREA_PAINTED = 1
    MORE_TOWERS = 2
    MORE_MONEY = 3
    MORE_STORED_PAINT = 4
    MORE_ROBOTS = 5
    RANDOM = 6
