# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

class WinType(object):
    AREA_PAINTED = 0
    MORE_TOWERS = 1
    MORE_MONEY = 2
    MORE_STORED_PAINT = 3
    MORE_ROBOTS = 4
    RANDOM = 5
