// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { AttackAction } from '../../battlecode/schema/attack-action';
import { BuildAction } from '../../battlecode/schema/build-action';
import { DamageAction } from '../../battlecode/schema/damage-action';
import { DieAction } from '../../battlecode/schema/die-action';
import { IndicatorDotAction } from '../../battlecode/schema/indicator-dot-action';
import { IndicatorLineAction } from '../../battlecode/schema/indicator-line-action';
import { IndicatorStringAction } from '../../battlecode/schema/indicator-string-action';
import { MarkAction } from '../../battlecode/schema/mark-action';
import { MessageAction } from '../../battlecode/schema/message-action';
import { MopAction } from '../../battlecode/schema/mop-action';
import { PaintAction } from '../../battlecode/schema/paint-action';
import { SpawnAction } from '../../battlecode/schema/spawn-action';
import { SplashAction } from '../../battlecode/schema/splash-action';
import { TransferAction } from '../../battlecode/schema/transfer-action';
import { UnmarkAction } from '../../battlecode/schema/unmark-action';
import { UnpaintAction } from '../../battlecode/schema/unpaint-action';
import { UpgradeAction } from '../../battlecode/schema/upgrade-action';


export enum Action {
  NONE = 0,
  DamageAction = 1,
  PaintAction = 2,
  UnpaintAction = 3,
  MarkAction = 4,
  UnmarkAction = 5,
  AttackAction = 6,
  SplashAction = 7,
  MopAction = 8,
  BuildAction = 9,
  TransferAction = 10,
  MessageAction = 11,
  SpawnAction = 12,
  DieAction = 13,
  UpgradeAction = 14,
  IndicatorStringAction = 15,
  IndicatorDotAction = 16,
  IndicatorLineAction = 17
}

export function unionToAction(
  type: Action,
  accessor: (obj:AttackAction|BuildAction|DamageAction|DieAction|IndicatorDotAction|IndicatorLineAction|IndicatorStringAction|MarkAction|MessageAction|MopAction|PaintAction|SpawnAction|SplashAction|TransferAction|UnmarkAction|UnpaintAction|UpgradeAction) => AttackAction|BuildAction|DamageAction|DieAction|IndicatorDotAction|IndicatorLineAction|IndicatorStringAction|MarkAction|MessageAction|MopAction|PaintAction|SpawnAction|SplashAction|TransferAction|UnmarkAction|UnpaintAction|UpgradeAction|null
): AttackAction|BuildAction|DamageAction|DieAction|IndicatorDotAction|IndicatorLineAction|IndicatorStringAction|MarkAction|MessageAction|MopAction|PaintAction|SpawnAction|SplashAction|TransferAction|UnmarkAction|UnpaintAction|UpgradeAction|null {
  switch(Action[type]) {
    case 'NONE': return null; 
    case 'DamageAction': return accessor(new DamageAction())! as DamageAction;
    case 'PaintAction': return accessor(new PaintAction())! as PaintAction;
    case 'UnpaintAction': return accessor(new UnpaintAction())! as UnpaintAction;
    case 'MarkAction': return accessor(new MarkAction())! as MarkAction;
    case 'UnmarkAction': return accessor(new UnmarkAction())! as UnmarkAction;
    case 'AttackAction': return accessor(new AttackAction())! as AttackAction;
    case 'SplashAction': return accessor(new SplashAction())! as SplashAction;
    case 'MopAction': return accessor(new MopAction())! as MopAction;
    case 'BuildAction': return accessor(new BuildAction())! as BuildAction;
    case 'TransferAction': return accessor(new TransferAction())! as TransferAction;
    case 'MessageAction': return accessor(new MessageAction())! as MessageAction;
    case 'SpawnAction': return accessor(new SpawnAction())! as SpawnAction;
    case 'DieAction': return accessor(new DieAction())! as DieAction;
    case 'UpgradeAction': return accessor(new UpgradeAction())! as UpgradeAction;
    case 'IndicatorStringAction': return accessor(new IndicatorStringAction())! as IndicatorStringAction;
    case 'IndicatorDotAction': return accessor(new IndicatorDotAction())! as IndicatorDotAction;
    case 'IndicatorLineAction': return accessor(new IndicatorLineAction())! as IndicatorLineAction;
    default: return null;
  }
}

export function unionListToAction(
  type: Action, 
  accessor: (index: number, obj:AttackAction|BuildAction|DamageAction|DieAction|IndicatorDotAction|IndicatorLineAction|IndicatorStringAction|MarkAction|MessageAction|MopAction|PaintAction|SpawnAction|SplashAction|TransferAction|UnmarkAction|UnpaintAction|UpgradeAction) => AttackAction|BuildAction|DamageAction|DieAction|IndicatorDotAction|IndicatorLineAction|IndicatorStringAction|MarkAction|MessageAction|MopAction|PaintAction|SpawnAction|SplashAction|TransferAction|UnmarkAction|UnpaintAction|UpgradeAction|null, 
  index: number
): AttackAction|BuildAction|DamageAction|DieAction|IndicatorDotAction|IndicatorLineAction|IndicatorStringAction|MarkAction|MessageAction|MopAction|PaintAction|SpawnAction|SplashAction|TransferAction|UnmarkAction|UnpaintAction|UpgradeAction|null {
  switch(Action[type]) {
    case 'NONE': return null; 
    case 'DamageAction': return accessor(index, new DamageAction())! as DamageAction;
    case 'PaintAction': return accessor(index, new PaintAction())! as PaintAction;
    case 'UnpaintAction': return accessor(index, new UnpaintAction())! as UnpaintAction;
    case 'MarkAction': return accessor(index, new MarkAction())! as MarkAction;
    case 'UnmarkAction': return accessor(index, new UnmarkAction())! as UnmarkAction;
    case 'AttackAction': return accessor(index, new AttackAction())! as AttackAction;
    case 'SplashAction': return accessor(index, new SplashAction())! as SplashAction;
    case 'MopAction': return accessor(index, new MopAction())! as MopAction;
    case 'BuildAction': return accessor(index, new BuildAction())! as BuildAction;
    case 'TransferAction': return accessor(index, new TransferAction())! as TransferAction;
    case 'MessageAction': return accessor(index, new MessageAction())! as MessageAction;
    case 'SpawnAction': return accessor(index, new SpawnAction())! as SpawnAction;
    case 'DieAction': return accessor(index, new DieAction())! as DieAction;
    case 'UpgradeAction': return accessor(index, new UpgradeAction())! as UpgradeAction;
    case 'IndicatorStringAction': return accessor(index, new IndicatorStringAction())! as IndicatorStringAction;
    case 'IndicatorDotAction': return accessor(index, new IndicatorDotAction())! as IndicatorDotAction;
    case 'IndicatorLineAction': return accessor(index, new IndicatorLineAction())! as IndicatorLineAction;
    default: return null;
  }
}
