// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { DieType } from '../../battlecode/schema/die-type';


/**
 * Indicates that a robot died and should be removed
 */
export class DieAction {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DieAction {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

/**
 * Id of the robot that died
 */
id():number {
  return this.bb!.readUint16(this.bb_pos);
}

dieType():DieType {
  return this.bb!.readInt8(this.bb_pos + 2);
}

static sizeOf():number {
  return 4;
}

static createDieAction(builder:flatbuffers.Builder, id: number, dieType: DieType):flatbuffers.Offset {
  builder.prep(2, 4);
  builder.pad(1);
  builder.writeInt8(dieType);
  builder.writeInt16(id);
  return builder.offset();
}

}
