// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class MessageAction {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MessageAction {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

id():number {
  return this.bb!.readUint16(this.bb_pos);
}

data():number {
  return this.bb!.readInt32(this.bb_pos + 4);
}

static sizeOf():number {
  return 8;
}

static createMessageAction(builder:flatbuffers.Builder, id: number, data: number):flatbuffers.Offset {
  builder.prep(4, 8);
  builder.writeInt32(data);
  builder.pad(2);
  builder.writeInt16(id);
  return builder.offset();
}

}
