// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum RobotType {
  PAINT_TOWER = 0,
  MONEY_TOWER = 1,
  DEFENSE_TOWER = 2,
  SOLDIER = 3,
  SPLASHER = 4,
  MOPPER = 5
}
