// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Adds a marker to the timeline at the current round
 */
export class TimelineMarkerAction {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TimelineMarkerAction {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTimelineMarkerAction(bb:flatbuffers.ByteBuffer, obj?:TimelineMarkerAction):TimelineMarkerAction {
  return (obj || new TimelineMarkerAction()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTimelineMarkerAction(bb:flatbuffers.ByteBuffer, obj?:TimelineMarkerAction):TimelineMarkerAction {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TimelineMarkerAction()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

label():string|null
label(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
label(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startTimelineMarkerAction(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addLabel(builder:flatbuffers.Builder, labelOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, labelOffset, 0);
}

static endTimelineMarkerAction(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTimelineMarkerAction(builder:flatbuffers.Builder, labelOffset:flatbuffers.Offset):flatbuffers.Offset {
  TimelineMarkerAction.startTimelineMarkerAction(builder);
  TimelineMarkerAction.addLabel(builder, labelOffset);
  return TimelineMarkerAction.endTimelineMarkerAction(builder);
}
}
