// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum WinType {
  AREA_PAINTED = 0,
  MORE_TOWERS = 1,
  MORE_MONEY = 2,
  MORE_STORED_PAINT = 3,
  MORE_ROBOTS = 4,
  RANDOM = 5
}
