// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum WinType {
  RESIGNATION = 0,
  AREA_PAINTED = 1,
  MORE_TOWERS = 2,
  MORE_MONEY = 3,
  MORE_STORED_PAINT = 4,
  MORE_ROBOTS = 5,
  RANDOM = 6
}
