"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.DieType = void 0;
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
var DieType;
(function (DieType) {
    DieType[DieType["UNKNOWN"] = 0] = "UNKNOWN";
    DieType[DieType["EXCEPTION"] = 1] = "EXCEPTION";
})(DieType || (exports.DieType = DieType = {}));
