"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.MarkAction = void 0;
/**
 * Visually indicate a tile marked with a color
 */
var MarkAction = /** @class */ (function () {
    function MarkAction() {
        this.bb = null;
        this.bb_pos = 0;
    }
    MarkAction.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    MarkAction.prototype.loc = function () {
        return this.bb.readUint16(this.bb_pos);
    };
    MarkAction.prototype.isSecondary = function () {
        return this.bb.readInt8(this.bb_pos + 2);
    };
    MarkAction.sizeOf = function () {
        return 4;
    };
    MarkAction.createMarkAction = function (builder, loc, isSecondary) {
        builder.prep(2, 4);
        builder.pad(1);
        builder.writeInt8(isSecondary);
        builder.writeInt16(loc);
        return builder.offset();
    };
    return MarkAction;
}());
exports.MarkAction = MarkAction;
