"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.RobotType = void 0;
var RobotType;
(function (RobotType) {
    RobotType[RobotType["PAINT_TOWER"] = 0] = "PAINT_TOWER";
    RobotType[RobotType["MONEY_TOWER"] = 1] = "MONEY_TOWER";
    RobotType[RobotType["DEFENSE_TOWER"] = 2] = "DEFENSE_TOWER";
    RobotType[RobotType["SOLDIER"] = 3] = "SOLDIER";
    RobotType[RobotType["SPLASHER"] = 4] = "SPLASHER";
    RobotType[RobotType["MOPPER"] = 5] = "MOPPER";
})(RobotType || (exports.RobotType = RobotType = {}));
