"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.SpawnAction = void 0;
/**
 * Indicate that this robot was spawned on this turn
 */
var SpawnAction = /** @class */ (function () {
    function SpawnAction() {
        this.bb = null;
        this.bb_pos = 0;
    }
    SpawnAction.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    /**
     * Id of the bot that spawned
     */
    SpawnAction.prototype.id = function () {
        return this.bb.readUint16(this.bb_pos);
    };
    SpawnAction.prototype.x = function () {
        return this.bb.readUint16(this.bb_pos + 2);
    };
    SpawnAction.prototype.y = function () {
        return this.bb.readUint16(this.bb_pos + 4);
    };
    SpawnAction.prototype.team = function () {
        return this.bb.readInt8(this.bb_pos + 6);
    };
    SpawnAction.prototype.robotType = function () {
        return this.bb.readInt8(this.bb_pos + 7);
    };
    SpawnAction.sizeOf = function () {
        return 8;
    };
    SpawnAction.createSpawnAction = function (builder, id, x, y, team, robotType) {
        builder.prep(2, 8);
        builder.writeInt8(robotType);
        builder.writeInt8(team);
        builder.writeInt16(y);
        builder.writeInt16(x);
        builder.writeInt16(id);
        return builder.offset();
    };
    return SpawnAction;
}());
exports.SpawnAction = SpawnAction;
