"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.SplashAction = void 0;
/**
 * Visually indicate a splash attack
 */
var SplashAction = /** @class */ (function () {
    function SplashAction() {
        this.bb = null;
        this.bb_pos = 0;
    }
    SplashAction.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    /**
     * Location of the splash attack
     */
    SplashAction.prototype.loc = function () {
        return this.bb.readUint16(this.bb_pos);
    };
    SplashAction.sizeOf = function () {
        return 2;
    };
    SplashAction.createSplashAction = function (builder, loc) {
        builder.prep(2, 2);
        builder.writeInt16(loc);
        return builder.offset();
    };
    return SplashAction;
}());
exports.SplashAction = SplashAction;
