"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransferAction = void 0;
/**
 * Visually indicate transferring paint from one robot to another
 */
var TransferAction = /** @class */ (function () {
    function TransferAction() {
        this.bb = null;
        this.bb_pos = 0;
    }
    TransferAction.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    /**
     * Id of the transfer target
     */
    TransferAction.prototype.id = function () {
        return this.bb.readUint16(this.bb_pos);
    };
    TransferAction.prototype.amount = function () {
        return this.bb.readInt32(this.bb_pos + 4);
    };
    TransferAction.sizeOf = function () {
        return 8;
    };
    TransferAction.createTransferAction = function (builder, id, amount) {
        builder.prep(4, 8);
        builder.writeInt32(amount);
        builder.pad(2);
        builder.writeInt16(id);
        return builder.offset();
    };
    return TransferAction;
}());
exports.TransferAction = TransferAction;
