"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.UnmarkAction = void 0;
/**
 * Visually indicate a tile's marker has been removed
 */
var UnmarkAction = /** @class */ (function () {
    function UnmarkAction() {
        this.bb = null;
        this.bb_pos = 0;
    }
    UnmarkAction.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    UnmarkAction.prototype.loc = function () {
        return this.bb.readUint16(this.bb_pos);
    };
    UnmarkAction.sizeOf = function () {
        return 2;
    };
    UnmarkAction.createUnmarkAction = function (builder, loc) {
        builder.prep(2, 2);
        builder.writeInt16(loc);
        return builder.offset();
    };
    return UnmarkAction;
}());
exports.UnmarkAction = UnmarkAction;
