"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpgradeAction = void 0;
/**
 * Visually indicate that a tower was upgraded
 */
var UpgradeAction = /** @class */ (function () {
    function UpgradeAction() {
        this.bb = null;
        this.bb_pos = 0;
    }
    UpgradeAction.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    /**
     * Id of the upgraded tower
     */
    UpgradeAction.prototype.id = function () {
        return this.bb.readUint16(this.bb_pos);
    };
    UpgradeAction.prototype.newHealth = function () {
        return this.bb.readInt32(this.bb_pos + 4);
    };
    UpgradeAction.prototype.newMaxHealth = function () {
        return this.bb.readInt32(this.bb_pos + 8);
    };
    UpgradeAction.prototype.newPaint = function () {
        return this.bb.readInt32(this.bb_pos + 12);
    };
    UpgradeAction.prototype.newMaxPaint = function () {
        return this.bb.readInt32(this.bb_pos + 16);
    };
    UpgradeAction.sizeOf = function () {
        return 20;
    };
    UpgradeAction.createUpgradeAction = function (builder, id, newHealth, newMaxHealth, newPaint, newMaxPaint) {
        builder.prep(4, 20);
        builder.writeInt32(newMaxPaint);
        builder.writeInt32(newPaint);
        builder.writeInt32(newMaxHealth);
        builder.writeInt32(newHealth);
        builder.pad(2);
        builder.writeInt16(id);
        return builder.offset();
    };
    return UpgradeAction;
}());
exports.UpgradeAction = UpgradeAction;
