// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

@SuppressWarnings("unused")
public final class Action {
  private Action() { }
  public static final byte NONE = 0;
  public static final byte DamageAction = 1;
  public static final byte PaintAction = 2;
  public static final byte UnpaintAction = 3;
  public static final byte MarkAction = 4;
  public static final byte UnmarkAction = 5;
  public static final byte AttackAction = 6;
  public static final byte SplashAction = 7;
  public static final byte MopAction = 8;
  public static final byte BuildAction = 9;
  public static final byte TransferAction = 10;
  public static final byte MessageAction = 11;
  public static final byte SpawnAction = 12;
  public static final byte DieAction = 13;
  public static final byte UpgradeAction = 14;
  public static final byte IndicatorStringAction = 15;
  public static final byte IndicatorDotAction = 16;
  public static final byte IndicatorLineAction = 17;

  public static final String[] names = { "NONE", "DamageAction", "PaintAction", "UnpaintAction", "MarkAction", "UnmarkAction", "AttackAction", "SplashAction", "MopAction", "BuildAction", "TransferAction", "MessageAction", "SpawnAction", "DieAction", "UpgradeAction", "IndicatorStringAction", "IndicatorDotAction", "IndicatorLineAction", };

  public static String name(int e) { return names[e]; }
}